# Generated by Django 2.2 on 2020-09-08 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200908_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 18, 32, 36, 474301)),
        ),
    ]
