# Generated by Django 2.2 on 2020-09-15 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200908_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 12, 13, 14, 116269)),
        ),
    ]
