# Generated by Django 2.2 on 2020-10-22 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200915_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 16, 28, 34, 32921)),
        ),
    ]
